import { createSlice } from "@reduxjs/toolkit";

interface Fund {
  id?: number;
  fund_name: string;
  fund_description: string;
  fund_size: number;
  fund_documents: any[];
}

interface List {
  results?: Fund[];
  count?: number;
}

// Define the initial state interface
interface InitialState {
  fundList: List; // Type for the fund list
}

// Initial state of the fundSlice
const initialState: InitialState = {
  fundList: {}, // Initial value for the fund list
};

// Create a slice for fund-related state management
const fundSlice = createSlice({
  name: "fundSlice", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer to set the fund list
    setFundList: (state: InitialState, { payload }) => ({ ...state, fundList: payload }), // Update fundList with the data payload
  },
});

// Export the reducer generated by createSlice
export default fundSlice.reducer;

// Export actions generated by createSlice
export const { setFundList } = fundSlice.actions;
